# Permalinks
#
permalink:           pretty

# Setup
title:               sfm
tagline:             ''
description:         'By <a href="https://twitter.com/roskideluge" target="_blank">@roskideluge</a>'
url:                 roskideluge.github.io
baseurl:             'https://roskideluge.github.io'
paginate:            5

# About/contact
author:
  name:              
  url:               https://twitter.com/roskideluge
  email:             roberto.delgado@gmail.com

# Custom vars
version:             1.0.0
