# Permalinks
#
permalink:           pretty

# Setup
title:               Here & There
tagline:             ''
description:         'Here & There is a collaborative art project'
url:                 handt.art
baseurl:             'https://roskideluge.github.io'
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             roberto@sfirstm.com

# Custom vars
version:             1.0.0
