# Permalinks
#
permalink:           pretty

# Setup
title:               Sample Blog
tagline:             ''
description:         'By <a href="https://twitter.com/sfirstm" target="_blank">@sfirstm</a>'
url:                 roskideluge.github.io
baseurl:             'https://roskideluge.github.io'
paginate:            5

# About/contact
author:
  name:              
  url:               https://twitter.com/sfirstm
  email:             roberto@sfirstm.co

# Custom vars
version:             1.0.0
