# Permalinks
#
permalink:           pretty

# Setup
title:               sfm
tagline:             ''
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 roskideluge.github.io
baseurl:             'https://roskideluge.github.io'
paginate:            5

# About/contact
author:
  name:              Roberto L. Delgado
  url:               https://twitter.com/roskideluge
  email:             roberto@sfirstm.co

# Custom vars
version:             1.0.0
